## Numpy array and basics
learn about numpy


In [17]:
import numpy as np

Creating arrays from list


In [18]:

arr_1d = np.array([1, 3, 4, 5, 5])
print("1D array:", arr_1d)


arr_2d = np.array([[1, 3, 4, 5, 5], [2, 2, 3, 4, 5]])
print("2D array:", arr_2d)

1D array: [1 3 4 5 5]
2D array: [[1 3 4 5 5]
 [2 2 3 4 5]]


### list vs numpy arrays

In [19]:
py_list = [1,2,3]
print("Python list multiplication:", py_list * 2)

np_array = np.array([1,2,3]) #elemnt wise multliplication
print("Python array multiplication:", np_array * 2)


Python list multiplication: [1, 2, 3, 1, 2, 3]
Python array multiplication: [2 4 6]


In [20]:
import time
start = time.time()
py_list = [i*2 for i in range(10000)]
print("\n numpy operation time", time.time() - start)


start = time.time() #faster than list comprehension
np_array = np.arange(10000)*2
print("\n numpy operation time", time.time() - start)


 numpy operation time 0.0034639835357666016

 numpy operation time 0.0006363391876220703


creating array from scratch

In [21]:
zeros = np.zeros((3, 4))# 3 rows 4 column
print("Zeros array:\n", zeros)


ones = np.ones((3, 4))# 3 rows 4 column
print("ones array:\n", ones)


full = np.full((3, 4), 3)# 3 rows 4 column
print("full array:\n", full)

random = np.random.random((3, 4))# 3 rows 4 column
print("random array:\n", random)

sequence = np.arange(1, 10, 2)  # start, stop, step
print("Sequence array: \n", sequence)


Zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
full array:
 [[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]
random array:
 [[0.16169583 0.0803527  0.98347175 0.69814881]
 [0.06534239 0.53586176 0.84516061 0.4269684 ]
 [0.82978016 0.30053645 0.86921568 0.01090932]]
Sequence array: 
 [1 3 5 7 9]


Vector,matrix and tensor

In [22]:
vector = np.array([1, 2, 3])
print("Vector array:", vector)


matrix = np.array([[1, 2, 3], 
                   [4, 5, 6]])
print("Matrix array:\n", matrix)


# Tensor is a multi-dimensional array like more than 2D
tensor = np.array([[[1, 2], [3, 4]], 
                   [[5, 6], [7, 8]]])
print("Tensor array:\n", tensor)

Vector array: [1 2 3]
Matrix array:
 [[1 2 3]
 [4 5 6]]
Tensor array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Arrays Properties

In [ ]:
arr = np.array([[1, 2, 3, 4, 5],
               [1, 2, 3, 4, 5]])  
print("Array with shape :", arr.shape)#it will give rows and columns of the array
print("Array with dimension :", arr.ndim)#tells how many dimensions the array has
print("Array with data type :", arr.dtype)#tells the data type of the array
print("Array with size :", arr.size)  # total number of elements in the array

### Array reshaping

In [ ]:
arr = np.arange(12)
print("original array", arr)


reshaped_arr = arr.reshape(3, 4)  # Reshape to 3 rows and 4 columns
print("\nReshaped array:\n", reshaped_arr)

# flattened return copy
flattened = reshaped_arr.flatten()  # Flatten the array to 1D
print("\nFlattened array:", flattened)

# ravel return view
raveled = reshaped_arr.ravel()  # Ravel the array to 1D
print("\nRaveled array:", raveled)

#transpose
arr = np.array([[1, 2, 3], [4, 5, 6]])
reshaped = arr.reshape(3, 2)  # Reshape into 3 rows, 2 columns
transpose = reshaped.T
print("\n Transposed", transpose)